version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    steps:
      - checkout
      - run:
         name: Deploy
         command: |
           ant -f . -Dnb.internal.action.name=test -Dignore.failing.tests=true -Dnb.wait.for.caches=true test

